name: hotei

services:
    pgsql:
        image: "postgres:15"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "hotei-pgsql:/var/lib/postgresql/data"
        networks:
            - hotei
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s

    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        env_file: .env
        # extra_hosts:
        #     - "host.docker.internal:host-gateway"
        ports:
            - "8000:8000"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        volumes:
            - ".:/var/www/html"
        networks:
            - hotei
        depends_on:
            - pgsql

networks:
    hotei:
        driver: bridge

volumes:
    hotei-pgsql:
        driver: local
    hotei-storage:
        driver: local